sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # download and un-encrypt file encrypted with travis-cli
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # install and setup gcloud for kubernetes
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project tut-multi-k8s
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials tut-multi-cluster
  # Login to docker CLI and build test container
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t tonymontaro/client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true tonymontaro/client-test npm run test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
