apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tut-multi-k8s-ga
spec:
  secretName: tut-multi-k8s-ga
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tut-multi-k8s.ga
  dnsNames:
    - tut-multi-k8s.ga
    - www.tut-multi-k8s.ga
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - tut-multi-k8s.ga
          - www.tut-multi-k8s.ga
